import createFetchClient, { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types/api/v1"; // generated by openapi-typescript
import { auth, reauthenticate } from "../firebase";
import { toast } from "@/lib/toast";

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    // Fetch fresh token on each request to ensure it's not stale
    const token = await auth.currentUser?.getIdToken();
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
};

// Throttle 403 toasts to avoid spamming user when multiple endpoints fail
let lastForbiddenToastTime = 0;
const FORBIDDEN_TOAST_THROTTLE_MS = 10000; // 10 seconds

const forbiddenMiddleware: Middleware = {
  onResponse({ response }) {
    if (response.status === 403) {
      const now = Date.now();
      if (now - lastForbiddenToastTime > FORBIDDEN_TOAST_THROTTLE_MS) {
        lastForbiddenToastTime = now;
        toast.error(
          "You need admin rights to access this. Please reach out to Quatt-cloud backend team.",
          {
            action: {
              label: "Re-authenticate",
              onClick: () => reauthenticate(),
            },
          },
        );
      }
    }
    return response;
  },
};

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_API_BASE_PATH as string,
});

fetchClient.use(authMiddleware);
fetchClient.use(forbiddenMiddleware);

export const $api = createClient(fetchClient);

// Default export for convenience
export default $api;
