import createFetchClient, { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types/api/v1"; // generated by openapi-typescript
import { auth } from "../firebase";

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    // Fetch fresh token on each request to ensure it's not stale
    const token = await auth.currentUser?.getIdToken();
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
};

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_API_BASE_PATH as string,
});
fetchClient.use(authMiddleware);

const client = createClient(fetchClient);

export default client;
