/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicDashboardAggregate } from "./CicDashboardAggregate";
import {
  CicDashboardAggregateFromJSON,
  CicDashboardAggregateFromJSONTyped,
  CicDashboardAggregateToJSON,
} from "./CicDashboardAggregate";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminDashboardCics200Response
 */
export interface AdminDashboardCics200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminDashboardCics200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {CicDashboardAggregate}
   * @memberof AdminDashboardCics200Response
   */
  result: CicDashboardAggregate;
}

/**
 * Check if a given object implements the AdminDashboardCics200Response interface.
 */
export function instanceOfAdminDashboardCics200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminDashboardCics200ResponseFromJSON(
  json: any,
): AdminDashboardCics200Response {
  return AdminDashboardCics200ResponseFromJSONTyped(json, false);
}

export function AdminDashboardCics200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminDashboardCics200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: CicDashboardAggregateFromJSON(json["result"]),
  };
}

export function AdminDashboardCics200ResponseToJSON(
  value?: AdminDashboardCics200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: CicDashboardAggregateToJSON(value.result),
  };
}
