/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminInstallationDetail } from "./AdminInstallationDetail";
import {
  AdminInstallationDetailFromJSON,
  AdminInstallationDetailFromJSONTyped,
  AdminInstallationDetailToJSON,
} from "./AdminInstallationDetail";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminGetInstallation200Response
 */
export interface AdminGetInstallation200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminGetInstallation200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminInstallationDetail}
   * @memberof AdminGetInstallation200Response
   */
  result: AdminInstallationDetail;
}

/**
 * Check if a given object implements the AdminGetInstallation200Response interface.
 */
export function instanceOfAdminGetInstallation200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminGetInstallation200ResponseFromJSON(
  json: any,
): AdminGetInstallation200Response {
  return AdminGetInstallation200ResponseFromJSONTyped(json, false);
}

export function AdminGetInstallation200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminGetInstallation200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminInstallationDetailFromJSON(json["result"]),
  };
}

export function AdminGetInstallation200ResponseToJSON(
  value?: AdminGetInstallation200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminInstallationDetailToJSON(value.result),
  };
}
