/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminInstallationsList } from "./AdminInstallationsList";
import {
  AdminInstallationsListFromJSON,
  AdminInstallationsListFromJSONTyped,
  AdminInstallationsListToJSON,
} from "./AdminInstallationsList";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminInstallationsList200Response
 */
export interface AdminInstallationsList200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminInstallationsList200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Array<AdminInstallationsList>}
   * @memberof AdminInstallationsList200Response
   */
  result: Array<AdminInstallationsList>;
}

/**
 * Check if a given object implements the AdminInstallationsList200Response interface.
 */
export function instanceOfAdminInstallationsList200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminInstallationsList200ResponseFromJSON(
  json: any,
): AdminInstallationsList200Response {
  return AdminInstallationsList200ResponseFromJSONTyped(json, false);
}

export function AdminInstallationsList200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminInstallationsList200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: (json["result"] as Array<any>).map(AdminInstallationsListFromJSON),
  };
}

export function AdminInstallationsList200ResponseToJSON(
  value?: AdminInstallationsList200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: (value.result as Array<any>).map(AdminInstallationsListToJSON),
  };
}
