/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCicState
 */
export interface AdminCicState {
  /**
   *
   * @type {number}
   * @memberof AdminCicState
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof AdminCicState
   */
  cicId: string;
  /**
   *
   * @type {number}
   * @memberof AdminCicState
   */
  cicCommissioningId?: number | null;
  /**
   *
   * @type {number}
   * @memberof AdminCicState
   */
  installationId?: number | null;
  /**
   *
   * @type {object}
   * @memberof AdminCicState
   */
  status: AdminCicStateStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof AdminCicState
   */
  startAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AdminCicState
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AdminCicState
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const AdminCicStateStatusEnum = {
  Active: "active",
  Registering: "registering",
  Factory: "factory",
  Service: "service",
  Dead: "dead",
} as const;
export type AdminCicStateStatusEnum =
  (typeof AdminCicStateStatusEnum)[keyof typeof AdminCicStateStatusEnum];

/**
 * Check if a given object implements the AdminCicState interface.
 */
export function instanceOfAdminCicState(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "cicId" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "startAt" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "updatedAt" in value;

  return isInstance;
}

export function AdminCicStateFromJSON(json: any): AdminCicState {
  return AdminCicStateFromJSONTyped(json, false);
}

export function AdminCicStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCicState {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    cicId: json["cicId"],
    cicCommissioningId: !exists(json, "cicCommissioningId")
      ? undefined
      : json["cicCommissioningId"],
    installationId: !exists(json, "installationId")
      ? undefined
      : json["installationId"],
    status: json["status"],
    startAt: new Date(json["startAt"]),
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function AdminCicStateToJSON(value?: AdminCicState | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    cicId: value.cicId,
    cicCommissioningId: value.cicCommissioningId,
    installationId: value.installationId,
    status: value.status,
    startAt: value.startAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
  };
}
