/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * This object will be used to display the current active prices for electricity and gas in the mobile app.
 * @export
 * @interface AdminDynamicPricesCurrentPrice
 */
export interface AdminDynamicPricesCurrentPrice {
  /**
   * The current active electricity price in EUR/kWh. Null when querying historical data.
   * @type {number}
   * @memberof AdminDynamicPricesCurrentPrice
   */
  electricity: number | null;
  /**
   * The current active gas price in EUR/m3h. Null when querying historical data.
   * @type {number}
   * @memberof AdminDynamicPricesCurrentPrice
   */
  gas: number | null;
}

/**
 * Check if a given object implements the AdminDynamicPricesCurrentPrice interface.
 */
export function instanceOfAdminDynamicPricesCurrentPrice(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "electricity" in value;
  isInstance = isInstance && "gas" in value;

  return isInstance;
}

export function AdminDynamicPricesCurrentPriceFromJSON(
  json: any,
): AdminDynamicPricesCurrentPrice {
  return AdminDynamicPricesCurrentPriceFromJSONTyped(json, false);
}

export function AdminDynamicPricesCurrentPriceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminDynamicPricesCurrentPrice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    electricity: json["electricity"],
    gas: json["gas"],
  };
}

export function AdminDynamicPricesCurrentPriceToJSON(
  value?: AdminDynamicPricesCurrentPrice | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    electricity: value.electricity,
    gas: value.gas,
  };
}
