/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type AdminCicAllOfInProgressCommissioningRef
 * If there is a commissioning in progress, the commissioning reference. That can be a string (the commissioning UUID) or a number (the hybrid commissioning ID) for backward compatibility. Null if there is no commissioning in progress.
 * @export
 */
export type AdminCicAllOfInProgressCommissioningRef = number | string;

export function AdminCicAllOfInProgressCommissioningRefFromJSON(
  json: any,
): AdminCicAllOfInProgressCommissioningRef {
  return AdminCicAllOfInProgressCommissioningRefFromJSONTyped(json, false);
}

export function AdminCicAllOfInProgressCommissioningRefFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCicAllOfInProgressCommissioningRef {
  return json;
}

export function AdminCicAllOfInProgressCommissioningRefToJSON(
  value?: AdminCicAllOfInProgressCommissioningRef | null,
): any {
  return value as any;
}
