/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UserRole } from "./UserRole";
import {
  UserRoleFromJSON,
  UserRoleFromJSONTyped,
  UserRoleToJSON,
} from "./UserRole";

/**
 *
 * @export
 * @interface AdminCicSettingsUpdate
 */
export interface AdminCicSettingsUpdate {
  /**
   *
   * @type {string}
   * @memberof AdminCicSettingsUpdate
   */
  settingsId: string;
  /**
   *
   * @type {string}
   * @memberof AdminCicSettingsUpdate
   */
  cicId: string;
  /**
   *
   * @type {string}
   * @memberof AdminCicSettingsUpdate
   */
  userId: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminCicSettingsUpdate
   */
  updatedBy: string | null;
  /**
   *
   * @type {UserRole}
   * @memberof AdminCicSettingsUpdate
   */
  role: UserRole | null;
  /**
   *
   * @type {string}
   * @memberof AdminCicSettingsUpdate
   */
  settingsType: AdminCicSettingsUpdateSettingsTypeEnum;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof AdminCicSettingsUpdate
   */
  settings: { [key: string]: any };
  /**
   *
   * @type {number}
   * @memberof AdminCicSettingsUpdate
   */
  retries: number;
  /**
   *
   * @type {boolean}
   * @memberof AdminCicSettingsUpdate
   */
  supportsConfirmation: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdminCicSettingsUpdate
   */
  isUnconfirmed: boolean;
  /**
   *
   * @type {Date}
   * @memberof AdminCicSettingsUpdate
   */
  confirmedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AdminCicSettingsUpdate
   */
  cancelledAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AdminCicSettingsUpdate
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AdminCicSettingsUpdate
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const AdminCicSettingsUpdateSettingsTypeEnum = {
  Setting: "setting",
  Config: "config",
  NoSupportSplit: "noSupportSplit",
} as const;
export type AdminCicSettingsUpdateSettingsTypeEnum =
  (typeof AdminCicSettingsUpdateSettingsTypeEnum)[keyof typeof AdminCicSettingsUpdateSettingsTypeEnum];

/**
 * Check if a given object implements the AdminCicSettingsUpdate interface.
 */
export function instanceOfAdminCicSettingsUpdate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "settingsId" in value;
  isInstance = isInstance && "cicId" in value;
  isInstance = isInstance && "userId" in value;
  isInstance = isInstance && "updatedBy" in value;
  isInstance = isInstance && "role" in value;
  isInstance = isInstance && "settingsType" in value;
  isInstance = isInstance && "settings" in value;
  isInstance = isInstance && "retries" in value;
  isInstance = isInstance && "supportsConfirmation" in value;
  isInstance = isInstance && "isUnconfirmed" in value;
  isInstance = isInstance && "confirmedAt" in value;
  isInstance = isInstance && "cancelledAt" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "updatedAt" in value;

  return isInstance;
}

export function AdminCicSettingsUpdateFromJSON(
  json: any,
): AdminCicSettingsUpdate {
  return AdminCicSettingsUpdateFromJSONTyped(json, false);
}

export function AdminCicSettingsUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCicSettingsUpdate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    settingsId: json["settingsId"],
    cicId: json["cicId"],
    userId: json["userId"],
    updatedBy: json["updatedBy"],
    role: UserRoleFromJSON(json["role"]),
    settingsType: json["settingsType"],
    settings: json["settings"],
    retries: json["retries"],
    supportsConfirmation: json["supportsConfirmation"],
    isUnconfirmed: json["isUnconfirmed"],
    confirmedAt:
      json["confirmedAt"] === null ? null : new Date(json["confirmedAt"]),
    cancelledAt:
      json["cancelledAt"] === null ? null : new Date(json["cancelledAt"]),
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function AdminCicSettingsUpdateToJSON(
  value?: AdminCicSettingsUpdate | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    settingsId: value.settingsId,
    cicId: value.cicId,
    userId: value.userId,
    updatedBy: value.updatedBy,
    role: UserRoleToJSON(value.role),
    settingsType: value.settingsType,
    settings: value.settings,
    retries: value.retries,
    supportsConfirmation: value.supportsConfirmation,
    isUnconfirmed: value.isUnconfirmed,
    confirmedAt:
      value.confirmedAt === null ? null : value.confirmedAt.toISOString(),
    cancelledAt:
      value.cancelledAt === null ? null : value.cancelledAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
  };
}
