/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminInstallationsList
 */
export interface AdminInstallationsList {
  /**
   *
   * @type {string}
   * @memberof AdminInstallationsList
   */
  externalId: string;
  /**
   *
   * @type {string}
   * @memberof AdminInstallationsList
   */
  cicId: string;
  /**
   *
   * @type {string}
   * @memberof AdminInstallationsList
   */
  orderNumber: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminInstallationsList
   */
  hubspotDealId: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminInstallationsList
   */
  menderId: string | null;
  /**
   *
   * @type {Date}
   * @memberof AdminInstallationsList
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AdminInstallationsList
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the AdminInstallationsList interface.
 */
export function instanceOfAdminInstallationsList(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "externalId" in value;
  isInstance = isInstance && "cicId" in value;
  isInstance = isInstance && "orderNumber" in value;
  isInstance = isInstance && "hubspotDealId" in value;
  isInstance = isInstance && "menderId" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "updatedAt" in value;

  return isInstance;
}

export function AdminInstallationsListFromJSON(
  json: any,
): AdminInstallationsList {
  return AdminInstallationsListFromJSONTyped(json, false);
}

export function AdminInstallationsListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminInstallationsList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    externalId: json["externalId"],
    cicId: json["cicId"],
    orderNumber: json["orderNumber"],
    hubspotDealId: json["hubspotDealId"],
    menderId: json["menderId"],
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function AdminInstallationsListToJSON(
  value?: AdminInstallationsList | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    externalId: value.externalId,
    cicId: value.cicId,
    orderNumber: value.orderNumber,
    hubspotDealId: value.hubspotDealId,
    menderId: value.menderId,
    createdAt: value.createdAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
  };
}
