/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";
import type { ServiceJob } from "./ServiceJob";
import {
  ServiceJobFromJSON,
  ServiceJobFromJSONTyped,
  ServiceJobToJSON,
} from "./ServiceJob";

/**
 *
 * @export
 * @interface AdminGetInstallationTicketsZuper200Response
 */
export interface AdminGetInstallationTicketsZuper200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminGetInstallationTicketsZuper200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Array<ServiceJob>}
   * @memberof AdminGetInstallationTicketsZuper200Response
   */
  result: Array<ServiceJob> | null;
}

/**
 * Check if a given object implements the AdminGetInstallationTicketsZuper200Response interface.
 */
export function instanceOfAdminGetInstallationTicketsZuper200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminGetInstallationTicketsZuper200ResponseFromJSON(
  json: any,
): AdminGetInstallationTicketsZuper200Response {
  return AdminGetInstallationTicketsZuper200ResponseFromJSONTyped(json, false);
}

export function AdminGetInstallationTicketsZuper200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminGetInstallationTicketsZuper200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result:
      json["result"] === null
        ? null
        : (json["result"] as Array<any>).map(ServiceJobFromJSON),
  };
}

export function AdminGetInstallationTicketsZuper200ResponseToJSON(
  value?: AdminGetInstallationTicketsZuper200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result:
      value.result === null
        ? null
        : (value.result as Array<any>).map(ServiceJobToJSON),
  };
}
