/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";
import type { Ticket } from "./Ticket";
import { TicketFromJSON, TicketFromJSONTyped, TicketToJSON } from "./Ticket";

/**
 *
 * @export
 * @interface AdminGetInstallationTickets200Response
 */
export interface AdminGetInstallationTickets200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminGetInstallationTickets200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Array<Ticket>}
   * @memberof AdminGetInstallationTickets200Response
   */
  result: Array<Ticket> | null;
}

/**
 * Check if a given object implements the AdminGetInstallationTickets200Response interface.
 */
export function instanceOfAdminGetInstallationTickets200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminGetInstallationTickets200ResponseFromJSON(
  json: any,
): AdminGetInstallationTickets200Response {
  return AdminGetInstallationTickets200ResponseFromJSONTyped(json, false);
}

export function AdminGetInstallationTickets200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminGetInstallationTickets200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result:
      json["result"] === null
        ? null
        : (json["result"] as Array<any>).map(TicketFromJSON),
  };
}

export function AdminGetInstallationTickets200ResponseToJSON(
  value?: AdminGetInstallationTickets200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result:
      value.result === null
        ? null
        : (value.result as Array<any>).map(TicketToJSON),
  };
}
