/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminDynamicPricesCurrentPrice } from "./AdminDynamicPricesCurrentPrice";
import {
  AdminDynamicPricesCurrentPriceFromJSON,
  AdminDynamicPricesCurrentPriceFromJSONTyped,
  AdminDynamicPricesCurrentPriceToJSON,
} from "./AdminDynamicPricesCurrentPrice";
import type { DynamicPricesPrices } from "./DynamicPricesPrices";
import {
  DynamicPricesPricesFromJSON,
  DynamicPricesPricesFromJSONTyped,
  DynamicPricesPricesToJSON,
} from "./DynamicPricesPrices";

/**
 *
 * @export
 * @interface AdminDynamicPrices
 */
export interface AdminDynamicPrices {
  /**
   *
   * @type {DynamicPricesPrices}
   * @memberof AdminDynamicPrices
   */
  prices: DynamicPricesPrices;
  /**
   *
   * @type {AdminDynamicPricesCurrentPrice}
   * @memberof AdminDynamicPrices
   */
  currentPrice: AdminDynamicPricesCurrentPrice;
}

/**
 * Check if a given object implements the AdminDynamicPrices interface.
 */
export function instanceOfAdminDynamicPrices(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "prices" in value;
  isInstance = isInstance && "currentPrice" in value;

  return isInstance;
}

export function AdminDynamicPricesFromJSON(json: any): AdminDynamicPrices {
  return AdminDynamicPricesFromJSONTyped(json, false);
}

export function AdminDynamicPricesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminDynamicPrices {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    prices: DynamicPricesPricesFromJSON(json["prices"]),
    currentPrice: AdminDynamicPricesCurrentPriceFromJSON(json["currentPrice"]),
  };
}

export function AdminDynamicPricesToJSON(
  value?: AdminDynamicPrices | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    prices: DynamicPricesPricesToJSON(value.prices),
    currentPrice: AdminDynamicPricesCurrentPriceToJSON(value.currentPrice),
  };
}
