/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ChillRunningMode } from "./ChillRunningMode";
import {
  ChillRunningModeFromJSON,
  ChillRunningModeFromJSONTyped,
  ChillRunningModeToJSON,
} from "./ChillRunningMode";

/**
 * Common operational data fields shared between CHILL device diagnostics and realtime data
 * @export
 * @interface BaseChillMetrics
 */
export interface BaseChillMetrics {
  /**
   *
   * @type {ChillRunningMode}
   * @memberof BaseChillMetrics
   */
  runningMode: ChillRunningMode | null;
  /**
   * Compressor enable status
   * @type {boolean}
   * @memberof BaseChillMetrics
   */
  compressorEnabled: boolean | null;
  /**
   * Four-way valve state, true means the refrigerant cycle is reversed
   * @type {boolean}
   * @memberof BaseChillMetrics
   */
  fourWayValveReversed: boolean | null;
  /**
   * Solenoid-valve enable state
   * @type {boolean}
   * @memberof BaseChillMetrics
   */
  solenoidValveEnabled: boolean | null;
  /**
   * Actual fan speed in RPM
   * @type {number}
   * @memberof BaseChillMetrics
   */
  fanActualSpeedRPM: number | null;
  /**
   * Pump feedback speed in RPM
   * @type {number}
   * @memberof BaseChillMetrics
   */
  pumpFeedbackSpeedRPM: number | null;
  /**
   * Real-time ambient air temperature (T3) in °C
   * @type {number}
   * @memberof BaseChillMetrics
   */
  ambientTemperature: number | null;
  /**
   * Relative humidity in percentage
   * @type {number}
   * @memberof BaseChillMetrics
   */
  humidityPercentage: number | null;
  /**
   * Inlet CH water temperature (T4) in °C
   * @type {number}
   * @memberof BaseChillMetrics
   */
  inletChTemperature: number | null;
  /**
   * Outlet CH water temperature (T5) in °C
   * @type {number}
   * @memberof BaseChillMetrics
   */
  outletChTemperature: number | null;
  /**
   * True if condensation-water tank is present
   * @type {boolean}
   * @memberof BaseChillMetrics
   */
  condensationTankPresent: boolean | null;
  /**
   * Water-flow switch state (true = closed)
   * @type {boolean}
   * @memberof BaseChillMetrics
   */
  waterFlowSwitchClosed: boolean | null;
  /**
   * Active system failure conditions from CHILL control board
   * @type {Array<string>}
   * @memberof BaseChillMetrics
   */
  systemFailures: Array<string> | null;
  /**
   * Active system protection conditions from CHILL control board
   * @type {Array<string>}
   * @memberof BaseChillMetrics
   */
  systemProtections: Array<string> | null;
}

/**
 * Check if a given object implements the BaseChillMetrics interface.
 */
export function instanceOfBaseChillMetrics(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "runningMode" in value;
  isInstance = isInstance && "compressorEnabled" in value;
  isInstance = isInstance && "fourWayValveReversed" in value;
  isInstance = isInstance && "solenoidValveEnabled" in value;
  isInstance = isInstance && "fanActualSpeedRPM" in value;
  isInstance = isInstance && "pumpFeedbackSpeedRPM" in value;
  isInstance = isInstance && "ambientTemperature" in value;
  isInstance = isInstance && "humidityPercentage" in value;
  isInstance = isInstance && "inletChTemperature" in value;
  isInstance = isInstance && "outletChTemperature" in value;
  isInstance = isInstance && "condensationTankPresent" in value;
  isInstance = isInstance && "waterFlowSwitchClosed" in value;
  isInstance = isInstance && "systemFailures" in value;
  isInstance = isInstance && "systemProtections" in value;

  return isInstance;
}

export function BaseChillMetricsFromJSON(json: any): BaseChillMetrics {
  return BaseChillMetricsFromJSONTyped(json, false);
}

export function BaseChillMetricsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BaseChillMetrics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    runningMode: ChillRunningModeFromJSON(json["runningMode"]),
    compressorEnabled: json["compressorEnabled"],
    fourWayValveReversed: json["fourWayValveReversed"],
    solenoidValveEnabled: json["solenoidValveEnabled"],
    fanActualSpeedRPM: json["fanActualSpeedRPM"],
    pumpFeedbackSpeedRPM: json["pumpFeedbackSpeedRPM"],
    ambientTemperature: json["ambientTemperature"],
    humidityPercentage: json["humidityPercentage"],
    inletChTemperature: json["inletChTemperature"],
    outletChTemperature: json["outletChTemperature"],
    condensationTankPresent: json["condensationTankPresent"],
    waterFlowSwitchClosed: json["waterFlowSwitchClosed"],
    systemFailures: json["systemFailures"],
    systemProtections: json["systemProtections"],
  };
}

export function BaseChillMetricsToJSON(value?: BaseChillMetrics | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    runningMode: ChillRunningModeToJSON(value.runningMode),
    compressorEnabled: value.compressorEnabled,
    fourWayValveReversed: value.fourWayValveReversed,
    solenoidValveEnabled: value.solenoidValveEnabled,
    fanActualSpeedRPM: value.fanActualSpeedRPM,
    pumpFeedbackSpeedRPM: value.pumpFeedbackSpeedRPM,
    ambientTemperature: value.ambientTemperature,
    humidityPercentage: value.humidityPercentage,
    inletChTemperature: value.inletChTemperature,
    outletChTemperature: value.outletChTemperature,
    condensationTankPresent: value.condensationTankPresent,
    waterFlowSwitchClosed: value.waterFlowSwitchClosed,
    systemFailures: value.systemFailures,
    systemProtections: value.systemProtections,
  };
}
