/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChillRealtimeData
 */
export interface ChillRealtimeData {
  /**
   * Unix timestamp of last CIC stat update (milliseconds)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  timestamp: number | null;
  /**
   * Master on/off switch status
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  turnedOn: boolean;
  /**
   * ChillRunningMode enum (0-10)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  runningMode: number;
  /**
   * Compressor on/off status
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  compressorEnabled: boolean;
  /**
   * Four-way valve state (false=cooling mode, true=heating mode)
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  fourWayValveEnabled: boolean;
  /**
   * Inlet water temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  inletWaterTemp?: number | null;
  /**
   * Outlet water temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  outletWaterTemp?: number | null;
  /**
   * Ambient air temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  ambientTemp?: number | null;
  /**
   * Evaporator coil temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  evaporatorTemp?: number | null;
  /**
   * ChillFanMode enum (0=auto, 1=low, 2=high)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  fanMode: number;
  /**
   * Actual fan speed (RPM)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  fanSpeedRPM: number;
  /**
   * Target fan speed (RPM)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  fanTargetRPM: number;
  /**
   * Pump speed (RPM)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  pumpSpeedRPM: number;
  /**
   * Pump duty cycle (0-100%)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  pumpDutyCycle: number;
  /**
   * Cooling setpoint temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  coolingTargetTemp: number;
  /**
   * Heating setpoint temperature (�C)
   * @type {number}
   * @memberof ChillRealtimeData
   */
  heatingTargetTemp: number;
  /**
   * Water flow switch status (true=OK, false=issue)
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  waterFlowOk: boolean;
  /**
   * Condensation tank detected
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  condensationTankPresent: boolean;
  /**
   * True if any system failure flags are active
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  hasSystemFailures: boolean;
  /**
   * True if any system protection flags are active
   * @type {boolean}
   * @memberof ChillRealtimeData
   */
  hasSystemProtections: boolean;
}

/**
 * Check if a given object implements the ChillRealtimeData interface.
 */
export function instanceOfChillRealtimeData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "timestamp" in value;
  isInstance = isInstance && "turnedOn" in value;
  isInstance = isInstance && "runningMode" in value;
  isInstance = isInstance && "compressorEnabled" in value;
  isInstance = isInstance && "fourWayValveEnabled" in value;
  isInstance = isInstance && "fanMode" in value;
  isInstance = isInstance && "fanSpeedRPM" in value;
  isInstance = isInstance && "fanTargetRPM" in value;
  isInstance = isInstance && "pumpSpeedRPM" in value;
  isInstance = isInstance && "pumpDutyCycle" in value;
  isInstance = isInstance && "coolingTargetTemp" in value;
  isInstance = isInstance && "heatingTargetTemp" in value;
  isInstance = isInstance && "waterFlowOk" in value;
  isInstance = isInstance && "condensationTankPresent" in value;
  isInstance = isInstance && "hasSystemFailures" in value;
  isInstance = isInstance && "hasSystemProtections" in value;

  return isInstance;
}

export function ChillRealtimeDataFromJSON(json: any): ChillRealtimeData {
  return ChillRealtimeDataFromJSONTyped(json, false);
}

export function ChillRealtimeDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChillRealtimeData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    timestamp: json["timestamp"],
    turnedOn: json["turnedOn"],
    runningMode: json["runningMode"],
    compressorEnabled: json["compressorEnabled"],
    fourWayValveEnabled: json["fourWayValveEnabled"],
    inletWaterTemp: !exists(json, "inletWaterTemp")
      ? undefined
      : json["inletWaterTemp"],
    outletWaterTemp: !exists(json, "outletWaterTemp")
      ? undefined
      : json["outletWaterTemp"],
    ambientTemp: !exists(json, "ambientTemp") ? undefined : json["ambientTemp"],
    evaporatorTemp: !exists(json, "evaporatorTemp")
      ? undefined
      : json["evaporatorTemp"],
    fanMode: json["fanMode"],
    fanSpeedRPM: json["fanSpeedRPM"],
    fanTargetRPM: json["fanTargetRPM"],
    pumpSpeedRPM: json["pumpSpeedRPM"],
    pumpDutyCycle: json["pumpDutyCycle"],
    coolingTargetTemp: json["coolingTargetTemp"],
    heatingTargetTemp: json["heatingTargetTemp"],
    waterFlowOk: json["waterFlowOk"],
    condensationTankPresent: json["condensationTankPresent"],
    hasSystemFailures: json["hasSystemFailures"],
    hasSystemProtections: json["hasSystemProtections"],
  };
}

export function ChillRealtimeDataToJSON(value?: ChillRealtimeData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    timestamp: value.timestamp,
    turnedOn: value.turnedOn,
    runningMode: value.runningMode,
    compressorEnabled: value.compressorEnabled,
    fourWayValveEnabled: value.fourWayValveEnabled,
    inletWaterTemp: value.inletWaterTemp,
    outletWaterTemp: value.outletWaterTemp,
    ambientTemp: value.ambientTemp,
    evaporatorTemp: value.evaporatorTemp,
    fanMode: value.fanMode,
    fanSpeedRPM: value.fanSpeedRPM,
    fanTargetRPM: value.fanTargetRPM,
    pumpSpeedRPM: value.pumpSpeedRPM,
    pumpDutyCycle: value.pumpDutyCycle,
    coolingTargetTemp: value.coolingTargetTemp,
    heatingTargetTemp: value.heatingTargetTemp,
    waterFlowOk: value.waterFlowOk,
    condensationTankPresent: value.condensationTankPresent,
    hasSystemFailures: value.hasSystemFailures,
    hasSystemProtections: value.hasSystemProtections,
  };
}
