/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { BaseChillMetrics } from "./BaseChillMetrics";
import {
  BaseChillMetricsFromJSON,
  BaseChillMetricsFromJSONTyped,
  BaseChillMetricsToJSON,
} from "./BaseChillMetrics";
import type { DeviceStatus } from "./DeviceStatus";
import {
  DeviceStatusFromJSON,
  DeviceStatusFromJSONTyped,
  DeviceStatusToJSON,
} from "./DeviceStatus";

/**
 *
 * @export
 * @interface ChillDevice
 */
export interface ChillDevice {
  /**
   *
   * @type {string}
   * @memberof ChillDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof ChillDevice
   */
  cicUuid?: string | null;
  /**
   *
   * @type {string}
   * @memberof ChillDevice
   */
  name?: string | null;
  /**
   *
   * @type {DeviceStatus}
   * @memberof ChillDevice
   */
  status: DeviceStatus;
  /**
   *
   * @type {string}
   * @memberof ChillDevice
   */
  installationUuid?: string | null;
  /**
   *
   * @type {string}
   * @memberof ChillDevice
   */
  type: ChillDeviceTypeEnum;
  /**
   * Chill device serial number
   * @type {string}
   * @memberof ChillDevice
   */
  serialNumber: string;
  /**
   * Thread network hardware identifier (EUI-64)
   * @type {string}
   * @memberof ChillDevice
   */
  eui64: string;
  /**
   * PCB hardware version
   * @type {string}
   * @memberof ChillDevice
   */
  pcbHwVersion: string;
  /**
   *
   * @type {BaseChillMetrics}
   * @memberof ChillDevice
   */
  metrics?: BaseChillMetrics;
}

/**
 * @export
 */
export const ChillDeviceTypeEnum = {
  Chill: "CHILL",
} as const;
export type ChillDeviceTypeEnum =
  (typeof ChillDeviceTypeEnum)[keyof typeof ChillDeviceTypeEnum];

/**
 * Check if a given object implements the ChillDevice interface.
 */
export function instanceOfChillDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "serialNumber" in value;
  isInstance = isInstance && "eui64" in value;
  isInstance = isInstance && "pcbHwVersion" in value;

  return isInstance;
}

export function ChillDeviceFromJSON(json: any): ChillDevice {
  return ChillDeviceFromJSONTyped(json, false);
}

export function ChillDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChillDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    cicUuid: !exists(json, "cicUuid") ? undefined : json["cicUuid"],
    name: !exists(json, "name") ? undefined : json["name"],
    status: DeviceStatusFromJSON(json["status"]),
    installationUuid: !exists(json, "installationUuid")
      ? undefined
      : json["installationUuid"],
    type: json["type"],
    serialNumber: json["serialNumber"],
    eui64: json["eui64"],
    pcbHwVersion: json["pcbHwVersion"],
    metrics: !exists(json, "metrics")
      ? undefined
      : BaseChillMetricsFromJSON(json["metrics"]),
  };
}

export function ChillDeviceToJSON(value?: ChillDevice | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    cicUuid: value.cicUuid,
    name: value.name,
    status: DeviceStatusToJSON(value.status),
    installationUuid: value.installationUuid,
    type: value.type,
    serialNumber: value.serialNumber,
    eui64: value.eui64,
    pcbHwVersion: value.pcbHwVersion,
    metrics: BaseChillMetricsToJSON(value.metrics),
  };
}
