/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The running mode of the CHILL cooling device
 * @export
 */
export const ChillRunningMode = {
  Standby: "STANDBY",
  Cooling: "COOLING",
  Heating: "HEATING",
  Automatic: "AUTOMATIC",
  CommodityInspectionCool: "COMMODITY_INSPECTION_COOL",
  CommodityInspectionHeat: "COMMODITY_INSPECTION_HEAT",
  SubstrateMode: "SUBSTRATE_MODE",
} as const;
export type ChillRunningMode =
  (typeof ChillRunningMode)[keyof typeof ChillRunningMode];

export function ChillRunningModeFromJSON(json: any): ChillRunningMode {
  return ChillRunningModeFromJSONTyped(json, false);
}

export function ChillRunningModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChillRunningMode {
  return json as ChillRunningMode;
}

export function ChillRunningModeToJSON(value?: ChillRunningMode | null): any {
  return value as any;
}
