/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicAggregate } from "./CicAggregate";
import {
  CicAggregateFromJSON,
  CicAggregateFromJSONTyped,
  CicAggregateToJSON,
} from "./CicAggregate";

/**
 *
 * @export
 * @interface CicAggregateByKpi
 */
export interface CicAggregateByKpi {
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  registeredCicId: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  validSettings: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  isConnectedAWS: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  isConnectedInternet: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  hasLatestSoftware: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  isCommissioned: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  cloudConsistency: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  runningController: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  thermostatConnected: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  roomTemperatureControl: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  openthermBoilerConnected: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  heatpumpsConnected: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  cpuTemperature: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  loadAverage: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  watchdog: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  minimumCop: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  supervisoryControlMode: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  heatpumpErrors: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByKpi
   */
  numberOfRestarts: CicAggregate;
}

/**
 * Check if a given object implements the CicAggregateByKpi interface.
 */
export function instanceOfCicAggregateByKpi(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "registeredCicId" in value;
  isInstance = isInstance && "validSettings" in value;
  isInstance = isInstance && "isConnectedAWS" in value;
  isInstance = isInstance && "isConnectedInternet" in value;
  isInstance = isInstance && "hasLatestSoftware" in value;
  isInstance = isInstance && "isCommissioned" in value;
  isInstance = isInstance && "cloudConsistency" in value;
  isInstance = isInstance && "runningController" in value;
  isInstance = isInstance && "thermostatConnected" in value;
  isInstance = isInstance && "roomTemperatureControl" in value;
  isInstance = isInstance && "openthermBoilerConnected" in value;
  isInstance = isInstance && "heatpumpsConnected" in value;
  isInstance = isInstance && "cpuTemperature" in value;
  isInstance = isInstance && "loadAverage" in value;
  isInstance = isInstance && "watchdog" in value;
  isInstance = isInstance && "minimumCop" in value;
  isInstance = isInstance && "supervisoryControlMode" in value;
  isInstance = isInstance && "heatpumpErrors" in value;
  isInstance = isInstance && "numberOfRestarts" in value;

  return isInstance;
}

export function CicAggregateByKpiFromJSON(json: any): CicAggregateByKpi {
  return CicAggregateByKpiFromJSONTyped(json, false);
}

export function CicAggregateByKpiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicAggregateByKpi {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    registeredCicId: CicAggregateFromJSON(json["registeredCicId"]),
    validSettings: CicAggregateFromJSON(json["validSettings"]),
    isConnectedAWS: CicAggregateFromJSON(json["isConnectedAWS"]),
    isConnectedInternet: CicAggregateFromJSON(json["isConnectedInternet"]),
    hasLatestSoftware: CicAggregateFromJSON(json["hasLatestSoftware"]),
    isCommissioned: CicAggregateFromJSON(json["isCommissioned"]),
    cloudConsistency: CicAggregateFromJSON(json["cloudConsistency"]),
    runningController: CicAggregateFromJSON(json["runningController"]),
    thermostatConnected: CicAggregateFromJSON(json["thermostatConnected"]),
    roomTemperatureControl: CicAggregateFromJSON(
      json["roomTemperatureControl"],
    ),
    openthermBoilerConnected: CicAggregateFromJSON(
      json["openthermBoilerConnected"],
    ),
    heatpumpsConnected: CicAggregateFromJSON(json["heatpumpsConnected"]),
    cpuTemperature: CicAggregateFromJSON(json["cpuTemperature"]),
    loadAverage: CicAggregateFromJSON(json["loadAverage"]),
    watchdog: CicAggregateFromJSON(json["watchdog"]),
    minimumCop: CicAggregateFromJSON(json["minimumCop"]),
    supervisoryControlMode: CicAggregateFromJSON(
      json["supervisoryControlMode"],
    ),
    heatpumpErrors: CicAggregateFromJSON(json["heatpumpErrors"]),
    numberOfRestarts: CicAggregateFromJSON(json["numberOfRestarts"]),
  };
}

export function CicAggregateByKpiToJSON(value?: CicAggregateByKpi | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    registeredCicId: CicAggregateToJSON(value.registeredCicId),
    validSettings: CicAggregateToJSON(value.validSettings),
    isConnectedAWS: CicAggregateToJSON(value.isConnectedAWS),
    isConnectedInternet: CicAggregateToJSON(value.isConnectedInternet),
    hasLatestSoftware: CicAggregateToJSON(value.hasLatestSoftware),
    isCommissioned: CicAggregateToJSON(value.isCommissioned),
    cloudConsistency: CicAggregateToJSON(value.cloudConsistency),
    runningController: CicAggregateToJSON(value.runningController),
    thermostatConnected: CicAggregateToJSON(value.thermostatConnected),
    roomTemperatureControl: CicAggregateToJSON(value.roomTemperatureControl),
    openthermBoilerConnected: CicAggregateToJSON(
      value.openthermBoilerConnected,
    ),
    heatpumpsConnected: CicAggregateToJSON(value.heatpumpsConnected),
    cpuTemperature: CicAggregateToJSON(value.cpuTemperature),
    loadAverage: CicAggregateToJSON(value.loadAverage),
    watchdog: CicAggregateToJSON(value.watchdog),
    minimumCop: CicAggregateToJSON(value.minimumCop),
    supervisoryControlMode: CicAggregateToJSON(value.supervisoryControlMode),
    heatpumpErrors: CicAggregateToJSON(value.heatpumpErrors),
    numberOfRestarts: CicAggregateToJSON(value.numberOfRestarts),
  };
}
