/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CicAggregate
 */
export interface CicAggregate {
  /**
   * All good
   * @type {number}
   * @memberof CicAggregate
   */
  correct: number;
  /**
   * Warnings
   * @type {number}
   * @memberof CicAggregate
   */
  warning: number;
  /**
   * Errors
   * @type {number}
   * @memberof CicAggregate
   */
  error: number;
  /**
   * Not applicable
   * @type {number}
   * @memberof CicAggregate
   */
  notApplicable: number;
}

/**
 * Check if a given object implements the CicAggregate interface.
 */
export function instanceOfCicAggregate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "correct" in value;
  isInstance = isInstance && "warning" in value;
  isInstance = isInstance && "error" in value;
  isInstance = isInstance && "notApplicable" in value;

  return isInstance;
}

export function CicAggregateFromJSON(json: any): CicAggregate {
  return CicAggregateFromJSONTyped(json, false);
}

export function CicAggregateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicAggregate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    correct: json["correct"],
    warning: json["warning"],
    error: json["error"],
    notApplicable: json["notApplicable"],
  };
}

export function CicAggregateToJSON(value?: CicAggregate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    correct: value.correct,
    warning: value.warning,
    error: value.error,
    notApplicable: value.notApplicable,
  };
}
