/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicHealthCheckStatus } from "./CicHealthCheckStatus";
import {
  CicHealthCheckStatusFromJSON,
  CicHealthCheckStatusFromJSONTyped,
  CicHealthCheckStatusToJSON,
} from "./CicHealthCheckStatus";

/**
 *
 * @export
 * @interface CicHealthChecksByCategory
 */
export interface CicHealthChecksByCategory {
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  settings: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  connectivity: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  updates: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  io_connectivity: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  cic_software: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  controller: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthChecksByCategory
   */
  heatpump: CicHealthCheckStatus;
}

/**
 * Check if a given object implements the CicHealthChecksByCategory interface.
 */
export function instanceOfCicHealthChecksByCategory(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "settings" in value;
  isInstance = isInstance && "connectivity" in value;
  isInstance = isInstance && "updates" in value;
  isInstance = isInstance && "io_connectivity" in value;
  isInstance = isInstance && "cic_software" in value;
  isInstance = isInstance && "controller" in value;
  isInstance = isInstance && "heatpump" in value;

  return isInstance;
}

export function CicHealthChecksByCategoryFromJSON(
  json: any,
): CicHealthChecksByCategory {
  return CicHealthChecksByCategoryFromJSONTyped(json, false);
}

export function CicHealthChecksByCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicHealthChecksByCategory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    settings: CicHealthCheckStatusFromJSON(json["settings"]),
    connectivity: CicHealthCheckStatusFromJSON(json["connectivity"]),
    updates: CicHealthCheckStatusFromJSON(json["updates"]),
    io_connectivity: CicHealthCheckStatusFromJSON(json["io_connectivity"]),
    cic_software: CicHealthCheckStatusFromJSON(json["cic_software"]),
    controller: CicHealthCheckStatusFromJSON(json["controller"]),
    heatpump: CicHealthCheckStatusFromJSON(json["heatpump"]),
  };
}

export function CicHealthChecksByCategoryToJSON(
  value?: CicHealthChecksByCategory | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    settings: CicHealthCheckStatusToJSON(value.settings),
    connectivity: CicHealthCheckStatusToJSON(value.connectivity),
    updates: CicHealthCheckStatusToJSON(value.updates),
    io_connectivity: CicHealthCheckStatusToJSON(value.io_connectivity),
    cic_software: CicHealthCheckStatusToJSON(value.cic_software),
    controller: CicHealthCheckStatusToJSON(value.controller),
    heatpump: CicHealthCheckStatusToJSON(value.heatpump),
  };
}
