/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicHealthCheckCategory } from "./CicHealthCheckCategory";
import {
  CicHealthCheckCategoryFromJSON,
  CicHealthCheckCategoryFromJSONTyped,
  CicHealthCheckCategoryToJSON,
} from "./CicHealthCheckCategory";
import type { CicHealthCheckStatus } from "./CicHealthCheckStatus";
import {
  CicHealthCheckStatusFromJSON,
  CicHealthCheckStatusFromJSONTyped,
  CicHealthCheckStatusToJSON,
} from "./CicHealthCheckStatus";

/**
 *
 * @export
 * @interface CicHealthCheckEntry
 */
export interface CicHealthCheckEntry {
  /**
   *
   * @type {CicHealthCheckCategory}
   * @memberof CicHealthCheckEntry
   */
  category: CicHealthCheckCategory;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof CicHealthCheckEntry
   */
  status: CicHealthCheckStatus;
}

/**
 * Check if a given object implements the CicHealthCheckEntry interface.
 */
export function instanceOfCicHealthCheckEntry(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "category" in value;
  isInstance = isInstance && "status" in value;

  return isInstance;
}

export function CicHealthCheckEntryFromJSON(json: any): CicHealthCheckEntry {
  return CicHealthCheckEntryFromJSONTyped(json, false);
}

export function CicHealthCheckEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicHealthCheckEntry {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    category: CicHealthCheckCategoryFromJSON(json["category"]),
    status: CicHealthCheckStatusFromJSON(json["status"]),
  };
}

export function CicHealthCheckEntryToJSON(
  value?: CicHealthCheckEntry | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    category: CicHealthCheckCategoryToJSON(value.category),
    status: CicHealthCheckStatusToJSON(value.status),
  };
}
