/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicHealthCheckEntry } from "./CicHealthCheckEntry";
import {
  CicHealthCheckEntryFromJSON,
  CicHealthCheckEntryFromJSONTyped,
  CicHealthCheckEntryToJSON,
} from "./CicHealthCheckEntry";

/**
 *
 * @export
 * @interface CicHealthChecksByKpi
 */
export interface CicHealthChecksByKpi {
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  validSettings: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  isConnectedAWS: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  isConnectedInternet: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  hasLatestSoftware: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  isCommissioned: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  cloudConsistency: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  runningController: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  thermostatConnected: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  roomTemperatureControl: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  openthermBoilerConnected: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  heatpumpsConnected: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  cpuTemperature: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  loadAverage: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  watchdog: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  minimumCop: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  supervisoryControlMode: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  heatpumpErrors: CicHealthCheckEntry;
  /**
   *
   * @type {CicHealthCheckEntry}
   * @memberof CicHealthChecksByKpi
   */
  numberOfRestarts: CicHealthCheckEntry;
}

/**
 * Check if a given object implements the CicHealthChecksByKpi interface.
 */
export function instanceOfCicHealthChecksByKpi(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "validSettings" in value;
  isInstance = isInstance && "isConnectedAWS" in value;
  isInstance = isInstance && "isConnectedInternet" in value;
  isInstance = isInstance && "hasLatestSoftware" in value;
  isInstance = isInstance && "isCommissioned" in value;
  isInstance = isInstance && "cloudConsistency" in value;
  isInstance = isInstance && "runningController" in value;
  isInstance = isInstance && "thermostatConnected" in value;
  isInstance = isInstance && "roomTemperatureControl" in value;
  isInstance = isInstance && "openthermBoilerConnected" in value;
  isInstance = isInstance && "heatpumpsConnected" in value;
  isInstance = isInstance && "cpuTemperature" in value;
  isInstance = isInstance && "loadAverage" in value;
  isInstance = isInstance && "watchdog" in value;
  isInstance = isInstance && "minimumCop" in value;
  isInstance = isInstance && "supervisoryControlMode" in value;
  isInstance = isInstance && "heatpumpErrors" in value;
  isInstance = isInstance && "numberOfRestarts" in value;

  return isInstance;
}

export function CicHealthChecksByKpiFromJSON(json: any): CicHealthChecksByKpi {
  return CicHealthChecksByKpiFromJSONTyped(json, false);
}

export function CicHealthChecksByKpiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicHealthChecksByKpi {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    validSettings: CicHealthCheckEntryFromJSON(json["validSettings"]),
    isConnectedAWS: CicHealthCheckEntryFromJSON(json["isConnectedAWS"]),
    isConnectedInternet: CicHealthCheckEntryFromJSON(
      json["isConnectedInternet"],
    ),
    hasLatestSoftware: CicHealthCheckEntryFromJSON(json["hasLatestSoftware"]),
    isCommissioned: CicHealthCheckEntryFromJSON(json["isCommissioned"]),
    cloudConsistency: CicHealthCheckEntryFromJSON(json["cloudConsistency"]),
    runningController: CicHealthCheckEntryFromJSON(json["runningController"]),
    thermostatConnected: CicHealthCheckEntryFromJSON(
      json["thermostatConnected"],
    ),
    roomTemperatureControl: CicHealthCheckEntryFromJSON(
      json["roomTemperatureControl"],
    ),
    openthermBoilerConnected: CicHealthCheckEntryFromJSON(
      json["openthermBoilerConnected"],
    ),
    heatpumpsConnected: CicHealthCheckEntryFromJSON(json["heatpumpsConnected"]),
    cpuTemperature: CicHealthCheckEntryFromJSON(json["cpuTemperature"]),
    loadAverage: CicHealthCheckEntryFromJSON(json["loadAverage"]),
    watchdog: CicHealthCheckEntryFromJSON(json["watchdog"]),
    minimumCop: CicHealthCheckEntryFromJSON(json["minimumCop"]),
    supervisoryControlMode: CicHealthCheckEntryFromJSON(
      json["supervisoryControlMode"],
    ),
    heatpumpErrors: CicHealthCheckEntryFromJSON(json["heatpumpErrors"]),
    numberOfRestarts: CicHealthCheckEntryFromJSON(json["numberOfRestarts"]),
  };
}

export function CicHealthChecksByKpiToJSON(
  value?: CicHealthChecksByKpi | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    validSettings: CicHealthCheckEntryToJSON(value.validSettings),
    isConnectedAWS: CicHealthCheckEntryToJSON(value.isConnectedAWS),
    isConnectedInternet: CicHealthCheckEntryToJSON(value.isConnectedInternet),
    hasLatestSoftware: CicHealthCheckEntryToJSON(value.hasLatestSoftware),
    isCommissioned: CicHealthCheckEntryToJSON(value.isCommissioned),
    cloudConsistency: CicHealthCheckEntryToJSON(value.cloudConsistency),
    runningController: CicHealthCheckEntryToJSON(value.runningController),
    thermostatConnected: CicHealthCheckEntryToJSON(value.thermostatConnected),
    roomTemperatureControl: CicHealthCheckEntryToJSON(
      value.roomTemperatureControl,
    ),
    openthermBoilerConnected: CicHealthCheckEntryToJSON(
      value.openthermBoilerConnected,
    ),
    heatpumpsConnected: CicHealthCheckEntryToJSON(value.heatpumpsConnected),
    cpuTemperature: CicHealthCheckEntryToJSON(value.cpuTemperature),
    loadAverage: CicHealthCheckEntryToJSON(value.loadAverage),
    watchdog: CicHealthCheckEntryToJSON(value.watchdog),
    minimumCop: CicHealthCheckEntryToJSON(value.minimumCop),
    supervisoryControlMode: CicHealthCheckEntryToJSON(
      value.supervisoryControlMode,
    ),
    heatpumpErrors: CicHealthCheckEntryToJSON(value.heatpumpErrors),
    numberOfRestarts: CicHealthCheckEntryToJSON(value.numberOfRestarts),
  };
}
