/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CicHealthCheckCategory = {
  Settings: "settings",
  Connectivity: "connectivity",
  Updates: "updates",
  IoConnectivity: "io_connectivity",
  CicSoftware: "cic_software",
  Controller: "controller",
  Heatpump: "heatpump",
} as const;
export type CicHealthCheckCategory =
  (typeof CicHealthCheckCategory)[keyof typeof CicHealthCheckCategory];

export function CicHealthCheckCategoryFromJSON(
  json: any,
): CicHealthCheckCategory {
  return CicHealthCheckCategoryFromJSONTyped(json, false);
}

export function CicHealthCheckCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicHealthCheckCategory {
  return json as CicHealthCheckCategory;
}

export function CicHealthCheckCategoryToJSON(
  value?: CicHealthCheckCategory | null,
): any {
  return value as any;
}
