/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CicHealthCheckStatus = {
  Correct: "correct",
  Warning: "warning",
  Error: "error",
  NotApplicable: "notApplicable",
} as const;
export type CicHealthCheckStatus =
  (typeof CicHealthCheckStatus)[keyof typeof CicHealthCheckStatus];

export function CicHealthCheckStatusFromJSON(json: any): CicHealthCheckStatus {
  return CicHealthCheckStatusFromJSONTyped(json, false);
}

export function CicHealthCheckStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicHealthCheckStatus {
  return json as CicHealthCheckStatus;
}

export function CicHealthCheckStatusToJSON(
  value?: CicHealthCheckStatus | null,
): any {
  return value as any;
}
