/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HeatChargerCommissioningPrerequisiteDetails } from "./HeatChargerCommissioningPrerequisiteDetails";
import {
  instanceOfHeatChargerCommissioningPrerequisiteDetails,
  HeatChargerCommissioningPrerequisiteDetailsFromJSON,
  HeatChargerCommissioningPrerequisiteDetailsFromJSONTyped,
  HeatChargerCommissioningPrerequisiteDetailsToJSON,
} from "./HeatChargerCommissioningPrerequisiteDetails";
import type { ThreadCommissioningPrerequisiteDetails } from "./ThreadCommissioningPrerequisiteDetails";
import {
  instanceOfThreadCommissioningPrerequisiteDetails,
  ThreadCommissioningPrerequisiteDetailsFromJSON,
  ThreadCommissioningPrerequisiteDetailsFromJSONTyped,
  ThreadCommissioningPrerequisiteDetailsToJSON,
} from "./ThreadCommissioningPrerequisiteDetails";

/**
 * @type CommissioningPrerequisiteDetails
 *
 * @export
 */
export type CommissioningPrerequisiteDetails =
  | HeatChargerCommissioningPrerequisiteDetails
  | ThreadCommissioningPrerequisiteDetails;

export function CommissioningPrerequisiteDetailsFromJSON(
  json: any,
): CommissioningPrerequisiteDetails {
  return CommissioningPrerequisiteDetailsFromJSONTyped(json, false);
}

export function CommissioningPrerequisiteDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningPrerequisiteDetails {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...HeatChargerCommissioningPrerequisiteDetailsFromJSONTyped(json, true),
    ...ThreadCommissioningPrerequisiteDetailsFromJSONTyped(json, true),
  };
}

export function CommissioningPrerequisiteDetailsToJSON(
  value?: CommissioningPrerequisiteDetails | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  if (instanceOfHeatChargerCommissioningPrerequisiteDetails(value)) {
    return HeatChargerCommissioningPrerequisiteDetailsToJSON(
      value as HeatChargerCommissioningPrerequisiteDetails,
    );
  }
  if (instanceOfThreadCommissioningPrerequisiteDetails(value)) {
    return ThreadCommissioningPrerequisiteDetailsToJSON(
      value as ThreadCommissioningPrerequisiteDetails,
    );
  }

  return {};
}
