/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CreateTariff409ResponseAllOfMeta } from "./CreateTariff409ResponseAllOfMeta";
import {
  CreateTariff409ResponseAllOfMetaFromJSON,
  CreateTariff409ResponseAllOfMetaFromJSONTyped,
  CreateTariff409ResponseAllOfMetaToJSON,
} from "./CreateTariff409ResponseAllOfMeta";
import type { CreateTariff409ResponseAllOfResult } from "./CreateTariff409ResponseAllOfResult";
import {
  CreateTariff409ResponseAllOfResultFromJSON,
  CreateTariff409ResponseAllOfResultFromJSONTyped,
  CreateTariff409ResponseAllOfResultToJSON,
} from "./CreateTariff409ResponseAllOfResult";

/**
 *
 * @export
 * @interface CreateTariff409Response
 */
export interface CreateTariff409Response {
  /**
   *
   * @type {CreateTariff409ResponseAllOfMeta}
   * @memberof CreateTariff409Response
   */
  meta: CreateTariff409ResponseAllOfMeta;
  /**
   *
   * @type {CreateTariff409ResponseAllOfResult}
   * @memberof CreateTariff409Response
   */
  result: CreateTariff409ResponseAllOfResult;
}

/**
 * Check if a given object implements the CreateTariff409Response interface.
 */
export function instanceOfCreateTariff409Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function CreateTariff409ResponseFromJSON(
  json: any,
): CreateTariff409Response {
  return CreateTariff409ResponseFromJSONTyped(json, false);
}

export function CreateTariff409ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTariff409Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: CreateTariff409ResponseAllOfMetaFromJSON(json["meta"]),
    result: CreateTariff409ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function CreateTariff409ResponseToJSON(
  value?: CreateTariff409Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: CreateTariff409ResponseAllOfMetaToJSON(value.meta),
    result: CreateTariff409ResponseAllOfResultToJSON(value.result),
  };
}
