/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";
import type { Tariff } from "./Tariff";
import { TariffFromJSON, TariffFromJSONTyped, TariffToJSON } from "./Tariff";

/**
 *
 * @export
 * @interface CreateTariff200Response
 */
export interface CreateTariff200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof CreateTariff200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Tariff}
   * @memberof CreateTariff200Response
   */
  result: Tariff;
}

/**
 * Check if a given object implements the CreateTariff200Response interface.
 */
export function instanceOfCreateTariff200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function CreateTariff200ResponseFromJSON(
  json: any,
): CreateTariff200Response {
  return CreateTariff200ResponseFromJSONTyped(json, false);
}

export function CreateTariff200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTariff200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: TariffFromJSON(json["result"]),
  };
}

export function CreateTariff200ResponseToJSON(
  value?: CreateTariff200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: TariffToJSON(value.result),
  };
}
