/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetAllTariffs200ResponseResult } from "./GetAllTariffs200ResponseResult";
import {
  GetAllTariffs200ResponseResultFromJSON,
  GetAllTariffs200ResponseResultFromJSONTyped,
  GetAllTariffs200ResponseResultToJSON,
} from "./GetAllTariffs200ResponseResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetAllTariffs200Response
 */
export interface GetAllTariffs200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetAllTariffs200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetAllTariffs200ResponseResult}
   * @memberof GetAllTariffs200Response
   */
  result: GetAllTariffs200ResponseResult;
}

/**
 * Check if a given object implements the GetAllTariffs200Response interface.
 */
export function instanceOfGetAllTariffs200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetAllTariffs200ResponseFromJSON(
  json: any,
): GetAllTariffs200Response {
  return GetAllTariffs200ResponseFromJSONTyped(json, false);
}

export function GetAllTariffs200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAllTariffs200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetAllTariffs200ResponseResultFromJSON(json["result"]),
  };
}

export function GetAllTariffs200ResponseToJSON(
  value?: GetAllTariffs200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetAllTariffs200ResponseResultToJSON(value.result),
  };
}
