/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminDynamicPrices } from "./AdminDynamicPrices";
import {
  AdminDynamicPricesFromJSON,
  AdminDynamicPricesFromJSONTyped,
  AdminDynamicPricesToJSON,
} from "./AdminDynamicPrices";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetAdminDynamicPrices200Response
 */
export interface GetAdminDynamicPrices200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetAdminDynamicPrices200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminDynamicPrices}
   * @memberof GetAdminDynamicPrices200Response
   */
  result: AdminDynamicPrices;
}

/**
 * Check if a given object implements the GetAdminDynamicPrices200Response interface.
 */
export function instanceOfGetAdminDynamicPrices200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetAdminDynamicPrices200ResponseFromJSON(
  json: any,
): GetAdminDynamicPrices200Response {
  return GetAdminDynamicPrices200ResponseFromJSONTyped(json, false);
}

export function GetAdminDynamicPrices200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAdminDynamicPrices200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminDynamicPricesFromJSON(json["result"]),
  };
}

export function GetAdminDynamicPrices200ResponseToJSON(
  value?: GetAdminDynamicPrices200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminDynamicPricesToJSON(value.result),
  };
}
