/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Commissioning } from "./Commissioning";
import {
  CommissioningFromJSON,
  CommissioningFromJSONTyped,
  CommissioningToJSON,
} from "./Commissioning";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetInstallerInstallationLatestCommissioning200Response
 */
export interface GetInstallerInstallationLatestCommissioning200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetInstallerInstallationLatestCommissioning200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Commissioning}
   * @memberof GetInstallerInstallationLatestCommissioning200Response
   */
  result: Commissioning;
}

/**
 * Check if a given object implements the GetInstallerInstallationLatestCommissioning200Response interface.
 */
export function instanceOfGetInstallerInstallationLatestCommissioning200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetInstallerInstallationLatestCommissioning200ResponseFromJSON(
  json: any,
): GetInstallerInstallationLatestCommissioning200Response {
  return GetInstallerInstallationLatestCommissioning200ResponseFromJSONTyped(
    json,
    false,
  );
}

export function GetInstallerInstallationLatestCommissioning200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInstallerInstallationLatestCommissioning200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: CommissioningFromJSON(json["result"]),
  };
}

export function GetInstallerInstallationLatestCommissioning200ResponseToJSON(
  value?: GetInstallerInstallationLatestCommissioning200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: CommissioningToJSON(value.result),
  };
}
