/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetMe500ResponseAllOfMeta } from "./GetMe500ResponseAllOfMeta";
import {
  GetMe500ResponseAllOfMetaFromJSON,
  GetMe500ResponseAllOfMetaFromJSONTyped,
  GetMe500ResponseAllOfMetaToJSON,
} from "./GetMe500ResponseAllOfMeta";
import type { GetMe500ResponseAllOfResult } from "./GetMe500ResponseAllOfResult";
import {
  GetMe500ResponseAllOfResultFromJSON,
  GetMe500ResponseAllOfResultFromJSONTyped,
  GetMe500ResponseAllOfResultToJSON,
} from "./GetMe500ResponseAllOfResult";

/**
 *
 * @export
 * @interface GetMe500Response
 */
export interface GetMe500Response {
  /**
   *
   * @type {GetMe500ResponseAllOfMeta}
   * @memberof GetMe500Response
   */
  meta: GetMe500ResponseAllOfMeta;
  /**
   *
   * @type {GetMe500ResponseAllOfResult}
   * @memberof GetMe500Response
   */
  result: GetMe500ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetMe500Response interface.
 */
export function instanceOfGetMe500Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetMe500ResponseFromJSON(json: any): GetMe500Response {
  return GetMe500ResponseFromJSONTyped(json, false);
}

export function GetMe500ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMe500Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: GetMe500ResponseAllOfMetaFromJSON(json["meta"]),
    result: GetMe500ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetMe500ResponseToJSON(value?: GetMe500Response | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: GetMe500ResponseAllOfMetaToJSON(value.meta),
    result: GetMe500ResponseAllOfResultToJSON(value.result),
  };
}
