/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetMe401ResponseAllOfMeta } from "./GetMe401ResponseAllOfMeta";
import {
  GetMe401ResponseAllOfMetaFromJSON,
  GetMe401ResponseAllOfMetaFromJSONTyped,
  GetMe401ResponseAllOfMetaToJSON,
} from "./GetMe401ResponseAllOfMeta";
import type { GetMe401ResponseAllOfResult } from "./GetMe401ResponseAllOfResult";
import {
  GetMe401ResponseAllOfResultFromJSON,
  GetMe401ResponseAllOfResultFromJSONTyped,
  GetMe401ResponseAllOfResultToJSON,
} from "./GetMe401ResponseAllOfResult";

/**
 *
 * @export
 * @interface GetMe401Response
 */
export interface GetMe401Response {
  /**
   *
   * @type {GetMe401ResponseAllOfMeta}
   * @memberof GetMe401Response
   */
  meta: GetMe401ResponseAllOfMeta;
  /**
   *
   * @type {GetMe401ResponseAllOfResult}
   * @memberof GetMe401Response
   */
  result: GetMe401ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetMe401Response interface.
 */
export function instanceOfGetMe401Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetMe401ResponseFromJSON(json: any): GetMe401Response {
  return GetMe401ResponseFromJSONTyped(json, false);
}

export function GetMe401ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMe401Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: GetMe401ResponseAllOfMetaFromJSON(json["meta"]),
    result: GetMe401ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetMe401ResponseToJSON(value?: GetMe401Response | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: GetMe401ResponseAllOfMetaToJSON(value.meta),
    result: GetMe401ResponseAllOfResultToJSON(value.result),
  };
}
