/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const HybridCommissioningIdentificationTestStatus = {
  Running: "running",
  Finished: "finished",
  Null: "null",
} as const;
export type HybridCommissioningIdentificationTestStatus =
  (typeof HybridCommissioningIdentificationTestStatus)[keyof typeof HybridCommissioningIdentificationTestStatus];

export function HybridCommissioningIdentificationTestStatusFromJSON(
  json: any,
): HybridCommissioningIdentificationTestStatus {
  return HybridCommissioningIdentificationTestStatusFromJSONTyped(json, false);
}

export function HybridCommissioningIdentificationTestStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningIdentificationTestStatus {
  return json as HybridCommissioningIdentificationTestStatus;
}

export function HybridCommissioningIdentificationTestStatusToJSON(
  value?: HybridCommissioningIdentificationTestStatus | null,
): any {
  return value as any;
}
