/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const HybridCommissioningIdentificationStatus = {
  Unidentified: "unidentified",
  Identified: "identified",
  Null: "null",
} as const;
export type HybridCommissioningIdentificationStatus =
  (typeof HybridCommissioningIdentificationStatus)[keyof typeof HybridCommissioningIdentificationStatus];

export function HybridCommissioningIdentificationStatusFromJSON(
  json: any,
): HybridCommissioningIdentificationStatus {
  return HybridCommissioningIdentificationStatusFromJSONTyped(json, false);
}

export function HybridCommissioningIdentificationStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningIdentificationStatus {
  return json as HybridCommissioningIdentificationStatus;
}

export function HybridCommissioningIdentificationStatusToJSON(
  value?: HybridCommissioningIdentificationStatus | null,
): any {
  return value as any;
}
