/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { HybridCommissioningFlowRateTestStatus } from "./HybridCommissioningFlowRateTestStatus";
import {
  HybridCommissioningFlowRateTestStatusFromJSON,
  HybridCommissioningFlowRateTestStatusFromJSONTyped,
  HybridCommissioningFlowRateTestStatusToJSON,
} from "./HybridCommissioningFlowRateTestStatus";
import type { HybridCommissioningHeatPumpPowerTest } from "./HybridCommissioningHeatPumpPowerTest";
import {
  HybridCommissioningHeatPumpPowerTestFromJSON,
  HybridCommissioningHeatPumpPowerTestFromJSONTyped,
  HybridCommissioningHeatPumpPowerTestToJSON,
} from "./HybridCommissioningHeatPumpPowerTest";
import type { HybridCommissioningHeatPumpTestLevel } from "./HybridCommissioningHeatPumpTestLevel";
import {
  HybridCommissioningHeatPumpTestLevelFromJSON,
  HybridCommissioningHeatPumpTestLevelFromJSONTyped,
  HybridCommissioningHeatPumpTestLevelToJSON,
} from "./HybridCommissioningHeatPumpTestLevel";
import type { HybridCommissioningIdentificationStatus } from "./HybridCommissioningIdentificationStatus";
import {
  HybridCommissioningIdentificationStatusFromJSON,
  HybridCommissioningIdentificationStatusFromJSONTyped,
  HybridCommissioningIdentificationStatusToJSON,
} from "./HybridCommissioningIdentificationStatus";
import type { HybridCommissioningIdentificationTestStatus } from "./HybridCommissioningIdentificationTestStatus";
import {
  HybridCommissioningIdentificationTestStatusFromJSON,
  HybridCommissioningIdentificationTestStatusFromJSONTyped,
  HybridCommissioningIdentificationTestStatusToJSON,
} from "./HybridCommissioningIdentificationTestStatus";
import type { HybridCommissioningMode } from "./HybridCommissioningMode";
import {
  HybridCommissioningModeFromJSON,
  HybridCommissioningModeFromJSONTyped,
  HybridCommissioningModeToJSON,
} from "./HybridCommissioningMode";

/**
 * A hybrid commissioning performed by an installer on a CiC
 * @export
 * @interface HybridCommissioning
 */
export interface HybridCommissioning {
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  thermostatIdentificationStatus: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  boilerIdentificationStatus?: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  heatPumpIdentificationStatus: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  heatPump1IdentificationStatus: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  heatPump2IdentificationStatus: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationStatus}
   * @memberof HybridCommissioning
   */
  flowTemperatureSensorIdentificationStatus: HybridCommissioningIdentificationStatus | null;
  /**
   *
   * @type {HybridCommissioningIdentificationTestStatus}
   * @memberof HybridCommissioning
   */
  identificationTestStatus: HybridCommissioningIdentificationTestStatus | null;
  /**
   * Amount of power in watt
   * @type {number}
   * @memberof HybridCommissioning
   */
  boilerPowerOnTestStop?: number | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  boilerTestStoppableAt?: Date | null;
  /**
   * When test is stopped and the minimum test period has been past, the cloud will set the deaerationTestStatus to finished. Else cancelled.
   * @type {string}
   * @memberof HybridCommissioning
   */
  deaerationTestStatus: HybridCommissioningDeaerationTestStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  deaerationStoppableAt: Date | null;
  /**
   *
   * @type {HybridCommissioningFlowRateTestStatus}
   * @memberof HybridCommissioning
   */
  flowRateTestStatus: HybridCommissioningFlowRateTestStatus | null;
  /**
   *
   * @type {HybridCommissioningFlowRateTestStatus}
   * @memberof HybridCommissioning
   */
  flowRateHp1TestStatus: HybridCommissioningFlowRateTestStatus | null;
  /**
   *
   * @type {HybridCommissioningFlowRateTestStatus}
   * @memberof HybridCommissioning
   */
  flowRateHp2TestStatus: HybridCommissioningFlowRateTestStatus | null;
  /**
   *
   * @type {HybridCommissioningFlowRateTestStatus}
   * @memberof HybridCommissioning
   */
  flowRateAllTestStatus: HybridCommissioningFlowRateTestStatus | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  flowRateHp1TestStoppableAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  flowRateHp2TestStoppableAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  flowRateAllTestStoppableAt: Date | null;
  /**
   * Flow rate on test stop
   * @type {number}
   * @memberof HybridCommissioning
   */
  flowRateOnTestStop: number | null;
  /**
   * Flow rate on test stop
   * @type {number}
   * @memberof HybridCommissioning
   */
  flowRateHp1OnTestStop?: number | null;
  /**
   * Flow rate on test stop
   * @type {number}
   * @memberof HybridCommissioning
   */
  flowRateHp2OnTestStop?: number | null;
  /**
   * Flow rate on test stop
   * @type {number}
   * @memberof HybridCommissioning
   */
  flowRateAllOnTestStop?: number | null;
  /**
   *
   * @type {string}
   * @memberof HybridCommissioning
   */
  heatPumpTestStatus: HybridCommissioningHeatPumpTestStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  heatPumpTestStoppableAt: Date | null;
  /**
   *
   * @type {HybridCommissioningHeatPumpTestLevel}
   * @memberof HybridCommissioning
   */
  heatPumpTestLevel?: HybridCommissioningHeatPumpTestLevel | null;
  /**
   *
   * @type {string}
   * @memberof HybridCommissioning
   */
  boilerTestStatus?: HybridCommissioningBoilerTestStatusEnum;
  /**
   *
   * @type {HybridCommissioningMode}
   * @memberof HybridCommissioning
   */
  commissioningMode: HybridCommissioningMode | null;
  /**
   * Whether the commissioning is forced
   * @type {boolean}
   * @memberof HybridCommissioning
   */
  isForced: boolean;
  /**
   * Whether the commissioning is cancelled
   * @type {boolean}
   * @memberof HybridCommissioning
   */
  isCancelled: boolean;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  completedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  createdAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof HybridCommissioning
   */
  updatedAt: Date | null;
  /**
   *
   * @type {Array<HybridCommissioningHeatPumpPowerTest>}
   * @memberof HybridCommissioning
   */
  heatPumps: Array<HybridCommissioningHeatPumpPowerTest>;
  /**
   * Whether the cic can start commissioning. Not application for the identification test
   * @type {boolean}
   * @memberof HybridCommissioning
   */
  canStartCommissioning?: boolean;
}

/**
 * @export
 */
export const HybridCommissioningDeaerationTestStatusEnum = {
  Finished: "finished",
  Running: "running",
  Cancelled: "cancelled",
} as const;
export type HybridCommissioningDeaerationTestStatusEnum =
  (typeof HybridCommissioningDeaerationTestStatusEnum)[keyof typeof HybridCommissioningDeaerationTestStatusEnum];

/**
 * @export
 */
export const HybridCommissioningHeatPumpTestStatusEnum = {
  Running: "running",
  PrePumping: "pre_pumping",
  PreHeating: "pre_heating",
  MinimumNotReached: "minimum_not_reached",
  MinimumReached: "minimum_reached",
  Finished: "finished",
  Cancelled: "cancelled",
  HeatPumpsReversed: "heat_pumps_reversed",
} as const;
export type HybridCommissioningHeatPumpTestStatusEnum =
  (typeof HybridCommissioningHeatPumpTestStatusEnum)[keyof typeof HybridCommissioningHeatPumpTestStatusEnum];

/**
 * @export
 */
export const HybridCommissioningBoilerTestStatusEnum = {
  MinimumReached: "minimum_reached",
  MinimumNotReached: "minimum_not_reached",
  Finished: "finished",
  Cancelled: "cancelled",
} as const;
export type HybridCommissioningBoilerTestStatusEnum =
  (typeof HybridCommissioningBoilerTestStatusEnum)[keyof typeof HybridCommissioningBoilerTestStatusEnum];

/**
 * Check if a given object implements the HybridCommissioning interface.
 */
export function instanceOfHybridCommissioning(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "thermostatIdentificationStatus" in value;
  isInstance = isInstance && "heatPumpIdentificationStatus" in value;
  isInstance = isInstance && "heatPump1IdentificationStatus" in value;
  isInstance = isInstance && "heatPump2IdentificationStatus" in value;
  isInstance =
    isInstance && "flowTemperatureSensorIdentificationStatus" in value;
  isInstance = isInstance && "identificationTestStatus" in value;
  isInstance = isInstance && "deaerationTestStatus" in value;
  isInstance = isInstance && "deaerationStoppableAt" in value;
  isInstance = isInstance && "flowRateTestStatus" in value;
  isInstance = isInstance && "flowRateHp1TestStatus" in value;
  isInstance = isInstance && "flowRateHp2TestStatus" in value;
  isInstance = isInstance && "flowRateAllTestStatus" in value;
  isInstance = isInstance && "flowRateHp1TestStoppableAt" in value;
  isInstance = isInstance && "flowRateHp2TestStoppableAt" in value;
  isInstance = isInstance && "flowRateAllTestStoppableAt" in value;
  isInstance = isInstance && "flowRateOnTestStop" in value;
  isInstance = isInstance && "heatPumpTestStatus" in value;
  isInstance = isInstance && "heatPumpTestStoppableAt" in value;
  isInstance = isInstance && "commissioningMode" in value;
  isInstance = isInstance && "isForced" in value;
  isInstance = isInstance && "isCancelled" in value;
  isInstance = isInstance && "completedAt" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "heatPumps" in value;

  return isInstance;
}

export function HybridCommissioningFromJSON(json: any): HybridCommissioning {
  return HybridCommissioningFromJSONTyped(json, false);
}

export function HybridCommissioningFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioning {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    thermostatIdentificationStatus:
      HybridCommissioningIdentificationStatusFromJSON(
        json["thermostatIdentificationStatus"],
      ),
    boilerIdentificationStatus: !exists(json, "boilerIdentificationStatus")
      ? undefined
      : HybridCommissioningIdentificationStatusFromJSON(
          json["boilerIdentificationStatus"],
        ),
    heatPumpIdentificationStatus:
      HybridCommissioningIdentificationStatusFromJSON(
        json["heatPumpIdentificationStatus"],
      ),
    heatPump1IdentificationStatus:
      HybridCommissioningIdentificationStatusFromJSON(
        json["heatPump1IdentificationStatus"],
      ),
    heatPump2IdentificationStatus:
      HybridCommissioningIdentificationStatusFromJSON(
        json["heatPump2IdentificationStatus"],
      ),
    flowTemperatureSensorIdentificationStatus:
      HybridCommissioningIdentificationStatusFromJSON(
        json["flowTemperatureSensorIdentificationStatus"],
      ),
    identificationTestStatus:
      HybridCommissioningIdentificationTestStatusFromJSON(
        json["identificationTestStatus"],
      ),
    boilerPowerOnTestStop: !exists(json, "boilerPowerOnTestStop")
      ? undefined
      : json["boilerPowerOnTestStop"],
    boilerTestStoppableAt: !exists(json, "boilerTestStoppableAt")
      ? undefined
      : json["boilerTestStoppableAt"] === null
        ? null
        : new Date(json["boilerTestStoppableAt"]),
    deaerationTestStatus: json["deaerationTestStatus"],
    deaerationStoppableAt:
      json["deaerationStoppableAt"] === null
        ? null
        : new Date(json["deaerationStoppableAt"]),
    flowRateTestStatus: HybridCommissioningFlowRateTestStatusFromJSON(
      json["flowRateTestStatus"],
    ),
    flowRateHp1TestStatus: HybridCommissioningFlowRateTestStatusFromJSON(
      json["flowRateHp1TestStatus"],
    ),
    flowRateHp2TestStatus: HybridCommissioningFlowRateTestStatusFromJSON(
      json["flowRateHp2TestStatus"],
    ),
    flowRateAllTestStatus: HybridCommissioningFlowRateTestStatusFromJSON(
      json["flowRateAllTestStatus"],
    ),
    flowRateHp1TestStoppableAt:
      json["flowRateHp1TestStoppableAt"] === null
        ? null
        : new Date(json["flowRateHp1TestStoppableAt"]),
    flowRateHp2TestStoppableAt:
      json["flowRateHp2TestStoppableAt"] === null
        ? null
        : new Date(json["flowRateHp2TestStoppableAt"]),
    flowRateAllTestStoppableAt:
      json["flowRateAllTestStoppableAt"] === null
        ? null
        : new Date(json["flowRateAllTestStoppableAt"]),
    flowRateOnTestStop: json["flowRateOnTestStop"],
    flowRateHp1OnTestStop: !exists(json, "flowRateHp1OnTestStop")
      ? undefined
      : json["flowRateHp1OnTestStop"],
    flowRateHp2OnTestStop: !exists(json, "flowRateHp2OnTestStop")
      ? undefined
      : json["flowRateHp2OnTestStop"],
    flowRateAllOnTestStop: !exists(json, "flowRateAllOnTestStop")
      ? undefined
      : json["flowRateAllOnTestStop"],
    heatPumpTestStatus: json["heatPumpTestStatus"],
    heatPumpTestStoppableAt:
      json["heatPumpTestStoppableAt"] === null
        ? null
        : new Date(json["heatPumpTestStoppableAt"]),
    heatPumpTestLevel: !exists(json, "heatPumpTestLevel")
      ? undefined
      : HybridCommissioningHeatPumpTestLevelFromJSON(json["heatPumpTestLevel"]),
    boilerTestStatus: !exists(json, "boilerTestStatus")
      ? undefined
      : json["boilerTestStatus"],
    commissioningMode: HybridCommissioningModeFromJSON(
      json["commissioningMode"],
    ),
    isForced: json["isForced"],
    isCancelled: json["isCancelled"],
    completedAt:
      json["completedAt"] === null ? null : new Date(json["completedAt"]),
    createdAt: json["createdAt"] === null ? null : new Date(json["createdAt"]),
    updatedAt: json["updatedAt"] === null ? null : new Date(json["updatedAt"]),
    heatPumps: (json["heatPumps"] as Array<any>).map(
      HybridCommissioningHeatPumpPowerTestFromJSON,
    ),
    canStartCommissioning: !exists(json, "canStartCommissioning")
      ? undefined
      : json["canStartCommissioning"],
  };
}

export function HybridCommissioningToJSON(
  value?: HybridCommissioning | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    thermostatIdentificationStatus:
      HybridCommissioningIdentificationStatusToJSON(
        value.thermostatIdentificationStatus,
      ),
    boilerIdentificationStatus: HybridCommissioningIdentificationStatusToJSON(
      value.boilerIdentificationStatus,
    ),
    heatPumpIdentificationStatus: HybridCommissioningIdentificationStatusToJSON(
      value.heatPumpIdentificationStatus,
    ),
    heatPump1IdentificationStatus:
      HybridCommissioningIdentificationStatusToJSON(
        value.heatPump1IdentificationStatus,
      ),
    heatPump2IdentificationStatus:
      HybridCommissioningIdentificationStatusToJSON(
        value.heatPump2IdentificationStatus,
      ),
    flowTemperatureSensorIdentificationStatus:
      HybridCommissioningIdentificationStatusToJSON(
        value.flowTemperatureSensorIdentificationStatus,
      ),
    identificationTestStatus: HybridCommissioningIdentificationTestStatusToJSON(
      value.identificationTestStatus,
    ),
    boilerPowerOnTestStop: value.boilerPowerOnTestStop,
    boilerTestStoppableAt:
      value.boilerTestStoppableAt === undefined
        ? undefined
        : value.boilerTestStoppableAt === null
          ? null
          : value.boilerTestStoppableAt.toISOString(),
    deaerationTestStatus: value.deaerationTestStatus,
    deaerationStoppableAt:
      value.deaerationStoppableAt === null
        ? null
        : value.deaerationStoppableAt.toISOString(),
    flowRateTestStatus: HybridCommissioningFlowRateTestStatusToJSON(
      value.flowRateTestStatus,
    ),
    flowRateHp1TestStatus: HybridCommissioningFlowRateTestStatusToJSON(
      value.flowRateHp1TestStatus,
    ),
    flowRateHp2TestStatus: HybridCommissioningFlowRateTestStatusToJSON(
      value.flowRateHp2TestStatus,
    ),
    flowRateAllTestStatus: HybridCommissioningFlowRateTestStatusToJSON(
      value.flowRateAllTestStatus,
    ),
    flowRateHp1TestStoppableAt:
      value.flowRateHp1TestStoppableAt === null
        ? null
        : value.flowRateHp1TestStoppableAt.toISOString(),
    flowRateHp2TestStoppableAt:
      value.flowRateHp2TestStoppableAt === null
        ? null
        : value.flowRateHp2TestStoppableAt.toISOString(),
    flowRateAllTestStoppableAt:
      value.flowRateAllTestStoppableAt === null
        ? null
        : value.flowRateAllTestStoppableAt.toISOString(),
    flowRateOnTestStop: value.flowRateOnTestStop,
    flowRateHp1OnTestStop: value.flowRateHp1OnTestStop,
    flowRateHp2OnTestStop: value.flowRateHp2OnTestStop,
    flowRateAllOnTestStop: value.flowRateAllOnTestStop,
    heatPumpTestStatus: value.heatPumpTestStatus,
    heatPumpTestStoppableAt:
      value.heatPumpTestStoppableAt === null
        ? null
        : value.heatPumpTestStoppableAt.toISOString(),
    heatPumpTestLevel: HybridCommissioningHeatPumpTestLevelToJSON(
      value.heatPumpTestLevel,
    ),
    boilerTestStatus: value.boilerTestStatus,
    commissioningMode: HybridCommissioningModeToJSON(value.commissioningMode),
    isForced: value.isForced,
    isCancelled: value.isCancelled,
    completedAt:
      value.completedAt === null ? null : value.completedAt.toISOString(),
    createdAt: value.createdAt === null ? null : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === null ? null : value.updatedAt.toISOString(),
    heatPumps: (value.heatPumps as Array<any>).map(
      HybridCommissioningHeatPumpPowerTestToJSON,
    ),
    canStartCommissioning: value.canStartCommissioning,
  };
}
