/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const HybridCommissioningHeatPumpTestLevel = {
  Medium: "medium",
  Maximum: "maximum",
  Null: "null",
} as const;
export type HybridCommissioningHeatPumpTestLevel =
  (typeof HybridCommissioningHeatPumpTestLevel)[keyof typeof HybridCommissioningHeatPumpTestLevel];

export function HybridCommissioningHeatPumpTestLevelFromJSON(
  json: any,
): HybridCommissioningHeatPumpTestLevel {
  return HybridCommissioningHeatPumpTestLevelFromJSONTyped(json, false);
}

export function HybridCommissioningHeatPumpTestLevelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningHeatPumpTestLevel {
  return json as HybridCommissioningHeatPumpTestLevel;
}

export function HybridCommissioningHeatPumpTestLevelToJSON(
  value?: HybridCommissioningHeatPumpTestLevel | null,
): any {
  return value as any;
}
