/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface HybridCommissioningHeatPumpPowerTest
 */
export interface HybridCommissioningHeatPumpPowerTest {
  /**
   *
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  modbusSlaveId: number;
  /**
   * PWM % on test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  pwmOnTestStop: number | null;
  /**
   * PWM % on hp1 test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  pwmOnFlowRateHp1TestStop: number | null;
  /**
   * PWM % on hp2 test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  pwmOnFlowRateHp2TestStop: number | null;
  /**
   * PWM % on all test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  pwmOnFlowRateAllTestStop: number | null;
  /**
   * Power in watt on medium test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  powerOnMediumTestStop: number | null;
  /**
   * Power in watt on maximum test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  powerOnMaximumTestStop: number | null;
  /**
   * Power in watt on test stop
   * @type {number}
   * @memberof HybridCommissioningHeatPumpPowerTest
   */
  powerOnTestStop: number | null;
}

/**
 * Check if a given object implements the HybridCommissioningHeatPumpPowerTest interface.
 */
export function instanceOfHybridCommissioningHeatPumpPowerTest(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "modbusSlaveId" in value;
  isInstance = isInstance && "pwmOnTestStop" in value;
  isInstance = isInstance && "pwmOnFlowRateHp1TestStop" in value;
  isInstance = isInstance && "pwmOnFlowRateHp2TestStop" in value;
  isInstance = isInstance && "pwmOnFlowRateAllTestStop" in value;
  isInstance = isInstance && "powerOnMediumTestStop" in value;
  isInstance = isInstance && "powerOnMaximumTestStop" in value;
  isInstance = isInstance && "powerOnTestStop" in value;

  return isInstance;
}

export function HybridCommissioningHeatPumpPowerTestFromJSON(
  json: any,
): HybridCommissioningHeatPumpPowerTest {
  return HybridCommissioningHeatPumpPowerTestFromJSONTyped(json, false);
}

export function HybridCommissioningHeatPumpPowerTestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningHeatPumpPowerTest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    modbusSlaveId: json["modbusSlaveId"],
    pwmOnTestStop: json["pwmOnTestStop"],
    pwmOnFlowRateHp1TestStop: json["pwmOnFlowRateHp1TestStop"],
    pwmOnFlowRateHp2TestStop: json["pwmOnFlowRateHp2TestStop"],
    pwmOnFlowRateAllTestStop: json["pwmOnFlowRateAllTestStop"],
    powerOnMediumTestStop: json["powerOnMediumTestStop"],
    powerOnMaximumTestStop: json["powerOnMaximumTestStop"],
    powerOnTestStop: json["powerOnTestStop"],
  };
}

export function HybridCommissioningHeatPumpPowerTestToJSON(
  value?: HybridCommissioningHeatPumpPowerTest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    modbusSlaveId: value.modbusSlaveId,
    pwmOnTestStop: value.pwmOnTestStop,
    pwmOnFlowRateHp1TestStop: value.pwmOnFlowRateHp1TestStop,
    pwmOnFlowRateHp2TestStop: value.pwmOnFlowRateHp2TestStop,
    pwmOnFlowRateAllTestStop: value.pwmOnFlowRateAllTestStop,
    powerOnMediumTestStop: value.powerOnMediumTestStop,
    powerOnMaximumTestStop: value.powerOnMaximumTestStop,
    powerOnTestStop: value.powerOnTestStop,
  };
}
