/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const HybridCommissioningFlowRateTestStatus = {
  Finished: "finished",
  MinimumReachedPending: "minimum_reached_pending",
  MinimumReached: "minimum_reached",
  MinimumNotReached: "minimum_not_reached",
  Cancelled: "cancelled",
} as const;
export type HybridCommissioningFlowRateTestStatus =
  (typeof HybridCommissioningFlowRateTestStatus)[keyof typeof HybridCommissioningFlowRateTestStatus];

export function HybridCommissioningFlowRateTestStatusFromJSON(
  json: any,
): HybridCommissioningFlowRateTestStatus {
  return HybridCommissioningFlowRateTestStatusFromJSONTyped(json, false);
}

export function HybridCommissioningFlowRateTestStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningFlowRateTestStatus {
  return json as HybridCommissioningFlowRateTestStatus;
}

export function HybridCommissioningFlowRateTestStatusToJSON(
  value?: HybridCommissioningFlowRateTestStatus | null,
): any {
  return value as any;
}
