/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const InstallationStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type InstallationStatus =
  (typeof InstallationStatus)[keyof typeof InstallationStatus];

export function InstallationStatusFromJSON(json: any): InstallationStatus {
  return InstallationStatusFromJSONTyped(json, false);
}

export function InstallationStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallationStatus {
  return json as InstallationStatus;
}

export function InstallationStatusToJSON(
  value?: InstallationStatus | null,
): any {
  return value as any;
}
