/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Avoid nighttime charging settings. Null when feature not supported, object when supported.
 * @export
 * @interface MeCicAllOfAvoidNighttimeCharging
 */
export interface MeCicAllOfAvoidNighttimeCharging {
  /**
   * When true, avoid charging during nighttime hours for all-electric installations
   * @type {boolean}
   * @memberof MeCicAllOfAvoidNighttimeCharging
   */
  allEAvoidNighttimeCharging: boolean;
  /**
   * Start time of the nighttime period in local time (e.g., "19:00")
   * @type {string}
   * @memberof MeCicAllOfAvoidNighttimeCharging
   */
  nighttimeChargingStartTime: string;
  /**
   * End time of the nighttime period in local time (e.g., "07:00")
   * @type {string}
   * @memberof MeCicAllOfAvoidNighttimeCharging
   */
  nighttimeChargingEndTime: string;
}

/**
 * Check if a given object implements the MeCicAllOfAvoidNighttimeCharging interface.
 */
export function instanceOfMeCicAllOfAvoidNighttimeCharging(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "allEAvoidNighttimeCharging" in value;
  isInstance = isInstance && "nighttimeChargingStartTime" in value;
  isInstance = isInstance && "nighttimeChargingEndTime" in value;

  return isInstance;
}

export function MeCicAllOfAvoidNighttimeChargingFromJSON(
  json: any,
): MeCicAllOfAvoidNighttimeCharging {
  return MeCicAllOfAvoidNighttimeChargingFromJSONTyped(json, false);
}

export function MeCicAllOfAvoidNighttimeChargingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MeCicAllOfAvoidNighttimeCharging {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    allEAvoidNighttimeCharging: json["allEAvoidNighttimeCharging"],
    nighttimeChargingStartTime: json["nighttimeChargingStartTime"],
    nighttimeChargingEndTime: json["nighttimeChargingEndTime"],
  };
}

export function MeCicAllOfAvoidNighttimeChargingToJSON(
  value?: MeCicAllOfAvoidNighttimeCharging | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    allEAvoidNighttimeCharging: value.allEAvoidNighttimeCharging,
    nighttimeChargingStartTime: value.nighttimeChargingStartTime,
    nighttimeChargingEndTime: value.nighttimeChargingEndTime,
  };
}
