/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ISO 3166-1 alpha-2 country code, e.g. NL or DE
 * @export
 */
export const NullableCountry = {
  Nl: "NL",
  De: "DE",
} as const;
export type NullableCountry =
  (typeof NullableCountry)[keyof typeof NullableCountry];

export function NullableCountryFromJSON(json: any): NullableCountry {
  return NullableCountryFromJSONTyped(json, false);
}

export function NullableCountryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NullableCountry {
  return json as NullableCountry;
}

export function NullableCountryToJSON(value?: NullableCountry | null): any {
  return value as any;
}
