/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServiceJob
 */
export interface ServiceJob {
  /**
   *
   * @type {string}
   * @memberof ServiceJob
   */
  job_uid: string;
  /**
   *
   * @type {string}
   * @memberof ServiceJob
   */
  job_title: string;
  /**
   *
   * @type {string}
   * @memberof ServiceJob
   */
  installer: string | null;
  /**
   *
   * @type {string}
   * @memberof ServiceJob
   */
  status_name: string;
  /**
   *
   * @type {Date}
   * @memberof ServiceJob
   */
  updated_at: Date;
}

/**
 * Check if a given object implements the ServiceJob interface.
 */
export function instanceOfServiceJob(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "job_uid" in value;
  isInstance = isInstance && "job_title" in value;
  isInstance = isInstance && "installer" in value;
  isInstance = isInstance && "status_name" in value;
  isInstance = isInstance && "updated_at" in value;

  return isInstance;
}

export function ServiceJobFromJSON(json: any): ServiceJob {
  return ServiceJobFromJSONTyped(json, false);
}

export function ServiceJobFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ServiceJob {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    job_uid: json["job_uid"],
    job_title: json["job_title"],
    installer: json["installer"],
    status_name: json["status_name"],
    updated_at: new Date(json["updated_at"]),
  };
}

export function ServiceJobToJSON(value?: ServiceJob | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    job_uid: value.job_uid,
    job_title: value.job_title,
    installer: value.installer,
    status_name: value.status_name,
    updated_at: value.updated_at.toISOString(),
  };
}
