/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ThreadDeviceUpdateState } from "./ThreadDeviceUpdateState";
import {
  ThreadDeviceUpdateStateFromJSON,
  ThreadDeviceUpdateStateFromJSONTyped,
  ThreadDeviceUpdateStateToJSON,
} from "./ThreadDeviceUpdateState";

/**
 * The prerequisites for the thread device to be ready for commissioning
 * @export
 * @interface ThreadCommissioningPrerequisiteDetails
 */
export interface ThreadCommissioningPrerequisiteDetails {
  /**
   * The current firmware version of the thread device
   * @type {string}
   * @memberof ThreadCommissioningPrerequisiteDetails
   */
  currentFirmwareVersion: string;
  /**
   *
   * @type {ThreadDeviceUpdateState}
   * @memberof ThreadCommissioningPrerequisiteDetails
   */
  updateState: ThreadDeviceUpdateState;
  /**
   * Whether the thread device is in update process
   * @type {boolean}
   * @memberof ThreadCommissioningPrerequisiteDetails
   */
  isInUpdateProcess: boolean;
}

/**
 * Check if a given object implements the ThreadCommissioningPrerequisiteDetails interface.
 */
export function instanceOfThreadCommissioningPrerequisiteDetails(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "currentFirmwareVersion" in value;
  isInstance = isInstance && "updateState" in value;
  isInstance = isInstance && "isInUpdateProcess" in value;

  return isInstance;
}

export function ThreadCommissioningPrerequisiteDetailsFromJSON(
  json: any,
): ThreadCommissioningPrerequisiteDetails {
  return ThreadCommissioningPrerequisiteDetailsFromJSONTyped(json, false);
}

export function ThreadCommissioningPrerequisiteDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ThreadCommissioningPrerequisiteDetails {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currentFirmwareVersion: json["currentFirmwareVersion"],
    updateState: ThreadDeviceUpdateStateFromJSON(json["updateState"]),
    isInUpdateProcess: json["isInUpdateProcess"],
  };
}

export function ThreadCommissioningPrerequisiteDetailsToJSON(
  value?: ThreadCommissioningPrerequisiteDetails | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    currentFirmwareVersion: value.currentFirmwareVersion,
    updateState: ThreadDeviceUpdateStateToJSON(value.updateState),
    isInUpdateProcess: value.isInUpdateProcess,
  };
}
