/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The update state of the firmware
 * @export
 */
export const ThreadDeviceUpdateState = {
  Unknown: "UNKNOWN",
  UpToDate: "UP_TO_DATE",
  PendingUpdate: "PENDING_UPDATE",
  UploadingImage: "UPLOADING_IMAGE",
  ValidatingImage: "VALIDATING_IMAGE",
  WaitingReboot: "WAITING_REBOOT",
  VerifyingUpdate: "VERIFYING_UPDATE",
  UpdateFailed: "UPDATE_FAILED",
} as const;
export type ThreadDeviceUpdateState =
  (typeof ThreadDeviceUpdateState)[keyof typeof ThreadDeviceUpdateState];

export function ThreadDeviceUpdateStateFromJSON(
  json: any,
): ThreadDeviceUpdateState {
  return ThreadDeviceUpdateStateFromJSONTyped(json, false);
}

export function ThreadDeviceUpdateStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ThreadDeviceUpdateState {
  return json as ThreadDeviceUpdateState;
}

export function ThreadDeviceUpdateStateToJSON(
  value?: ThreadDeviceUpdateState | null,
): any {
  return value as any;
}
