/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TicketHsPipelineStage
 */
export interface TicketHsPipelineStage {
  /**
   *
   * @type {string}
   * @memberof TicketHsPipelineStage
   */
  label?: string;
  /**
   *
   * @type {string}
   * @memberof TicketHsPipelineStage
   */
  value?: string;
}

/**
 * Check if a given object implements the TicketHsPipelineStage interface.
 */
export function instanceOfTicketHsPipelineStage(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TicketHsPipelineStageFromJSON(
  json: any,
): TicketHsPipelineStage {
  return TicketHsPipelineStageFromJSONTyped(json, false);
}

export function TicketHsPipelineStageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TicketHsPipelineStage {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    label: !exists(json, "label") ? undefined : json["label"],
    value: !exists(json, "value") ? undefined : json["value"],
  };
}

export function TicketHsPipelineStageToJSON(
  value?: TicketHsPipelineStage | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    label: value.label,
    value: value.value,
  };
}
