/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TicketHubspotOwnerId
 */
export interface TicketHubspotOwnerId {
  /**
   *
   * @type {string}
   * @memberof TicketHubspotOwnerId
   */
  owner_id?: string;
  /**
   *
   * @type {string}
   * @memberof TicketHubspotOwnerId
   */
  firstname?: string;
  /**
   *
   * @type {string}
   * @memberof TicketHubspotOwnerId
   */
  lastname?: string;
  /**
   *
   * @type {string}
   * @memberof TicketHubspotOwnerId
   */
  email?: string;
}

/**
 * Check if a given object implements the TicketHubspotOwnerId interface.
 */
export function instanceOfTicketHubspotOwnerId(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TicketHubspotOwnerIdFromJSON(json: any): TicketHubspotOwnerId {
  return TicketHubspotOwnerIdFromJSONTyped(json, false);
}

export function TicketHubspotOwnerIdFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TicketHubspotOwnerId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    owner_id: !exists(json, "owner_id") ? undefined : json["owner_id"],
    firstname: !exists(json, "firstname") ? undefined : json["firstname"],
    lastname: !exists(json, "lastname") ? undefined : json["lastname"],
    email: !exists(json, "email") ? undefined : json["email"],
  };
}

export function TicketHubspotOwnerIdToJSON(
  value?: TicketHubspotOwnerId | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    owner_id: value.owner_id,
    firstname: value.firstname,
    lastname: value.lastname,
    email: value.email,
  };
}
