/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UpdateUserClient404ResponseAllOfMeta } from "./UpdateUserClient404ResponseAllOfMeta";
import {
  UpdateUserClient404ResponseAllOfMetaFromJSON,
  UpdateUserClient404ResponseAllOfMetaFromJSONTyped,
  UpdateUserClient404ResponseAllOfMetaToJSON,
} from "./UpdateUserClient404ResponseAllOfMeta";
import type { UpdateUserClient404ResponseAllOfResult } from "./UpdateUserClient404ResponseAllOfResult";
import {
  UpdateUserClient404ResponseAllOfResultFromJSON,
  UpdateUserClient404ResponseAllOfResultFromJSONTyped,
  UpdateUserClient404ResponseAllOfResultToJSON,
} from "./UpdateUserClient404ResponseAllOfResult";

/**
 *
 * @export
 * @interface UpdateUserClient404Response
 */
export interface UpdateUserClient404Response {
  /**
   *
   * @type {UpdateUserClient404ResponseAllOfMeta}
   * @memberof UpdateUserClient404Response
   */
  meta: UpdateUserClient404ResponseAllOfMeta;
  /**
   *
   * @type {UpdateUserClient404ResponseAllOfResult}
   * @memberof UpdateUserClient404Response
   */
  result: UpdateUserClient404ResponseAllOfResult;
}

/**
 * Check if a given object implements the UpdateUserClient404Response interface.
 */
export function instanceOfUpdateUserClient404Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function UpdateUserClient404ResponseFromJSON(
  json: any,
): UpdateUserClient404Response {
  return UpdateUserClient404ResponseFromJSONTyped(json, false);
}

export function UpdateUserClient404ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserClient404Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: UpdateUserClient404ResponseAllOfMetaFromJSON(json["meta"]),
    result: UpdateUserClient404ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function UpdateUserClient404ResponseToJSON(
  value?: UpdateUserClient404Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: UpdateUserClient404ResponseAllOfMetaToJSON(value.meta),
    result: UpdateUserClient404ResponseAllOfResultToJSON(value.result),
  };
}
