/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Avoid nighttime charging settings. Only the allEAvoidNighttimeCharging field can be updated.
 * @export
 * @interface UpdateCicSharedPropertiesAvoidNighttimeCharging
 */
export interface UpdateCicSharedPropertiesAvoidNighttimeCharging {
  /**
   * When true, avoid charging during nighttime hours for all-electric installations
   * @type {boolean}
   * @memberof UpdateCicSharedPropertiesAvoidNighttimeCharging
   */
  allEAvoidNighttimeCharging?: boolean;
}

/**
 * Check if a given object implements the UpdateCicSharedPropertiesAvoidNighttimeCharging interface.
 */
export function instanceOfUpdateCicSharedPropertiesAvoidNighttimeCharging(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateCicSharedPropertiesAvoidNighttimeChargingFromJSON(
  json: any,
): UpdateCicSharedPropertiesAvoidNighttimeCharging {
  return UpdateCicSharedPropertiesAvoidNighttimeChargingFromJSONTyped(
    json,
    false,
  );
}

export function UpdateCicSharedPropertiesAvoidNighttimeChargingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCicSharedPropertiesAvoidNighttimeCharging {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    allEAvoidNighttimeCharging: !exists(json, "allEAvoidNighttimeCharging")
      ? undefined
      : json["allEAvoidNighttimeCharging"],
  };
}

export function UpdateCicSharedPropertiesAvoidNighttimeChargingToJSON(
  value?: UpdateCicSharedPropertiesAvoidNighttimeCharging | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    allEAvoidNighttimeCharging: value.allEAvoidNighttimeCharging,
  };
}
